### ISSUE TITLE
File format error ; Quinton_WGD_2020

### ISSUE THREAD

**Issue by paulahsan** [campbio/Manuscripts#5]
The *zip file for *Quinton_WGD_2020* is not unzipping.
Even after cloning the whole `Manuscript` the *Quinton_WGD_2020* seems empty

**Comment by SmallPackage** [comment]
> 
> 
> The *zip file for _Quinton_WGD_2020_ is not unzipping.
> Even after cloning the whole `Manuscript` the _Quinton_WGD_2020_ seems empty


have a look at: https://git-lfs.github.com/

After set up  GIT LFS,  you would get a different error:

`Downloading Quinton_WGD_2020/Final_Analysis.zip (1.0 GB)                                                                                                                                                         Error downloading object: Quinton_WGD_2020/Final_Analysis.zip (393f286): Smudge error: Error downloading Quinton_WGD_2020/Final_Analysis.zip (393f286a7e32821aad51a5796bfcff06a567c63b70c06f3a9def626a04a34060): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access. `

**Comment by joshua-d-campbell** [comment]
Hi @paulahsan and @SmallPackage 
Yes, we were using Git LFS for store the large zip file, but we didn't realize the download link in GitHub doesn't directly work. You would probably have to have your own LSF subscription to clone the repo and get the file.  To make it easier to retrieve most of the analysis, I have pushed new subfolders (Mutation, Expression, Dependency) that contain the scripts and output. I left out a few of the large input files to keep the size lower. However, these files are available online. The Dependency files can be found on the [DepMap](https://depmap.org/portal/) website. The TCGA expression, CNV, and clinical files can be found on the [PanCanAtlas](https://gdc.cancer.gov/about-data/publications/pancanatlas) data website. Note the links to input files used in the Mutation and Expression analyses are also posted in thee corresponding html analysis files:

`Mutation/Analysis/20200510_WGD_MutationAnalysis/20200510_WGD_MutationAnalysis.html`
`Expression/Analysis/20200510_WGD_ExpressionAnalysis/20200510_WGD_ExpressionAnalysis.html`

To rerun any of the analyses, you can put the input files back in the Data directories within each subdirectory. Hope that helps. I'm going to close the issue for now, but let me know if you run into other problems and thanks for your interest in our work.
